### ISSUE TITLE
Transaction endpoints not serializing amount

### ISSUE THREAD

**Issue by JoeWoodward** [omisego/ewallet#107]
When using the `ruby-sdk` I noticed that the transactions endpoints don't return the amount that was processed for a given transaction. I believe these endpoints are using this serializer (I have limited elixir exposure so don't trust me 😬) https://github.com/omisego/ewallet/blob/develop/apps/ewallet_api/lib/ewallet_api/v1/serializers/json/transaction_serializer.ex 

# Your environment

local rails app using `omisego` gem connecting to the eWallet API (omise private test env)

# Expected behaviour

When calling `OmiseGO::Transaction#all_for_user` I expect `amount` to be serialized and returned in the response. 

# Actual behavior

`amount` is not serialized

**Comment by unnawut** [comment]
I believe the discussion continued via Rocket Chat with @T-Dnzt. Let me know if you've resolved this issue. :)

**Comment by T-Dnzt** [comment]
`amount` is now available in the `from` and `to` fields since transaction can happen between two currencies with different amounts. 

Closing this for now, we will update the Ruby SDK to remove the unnecessary `amount` field at the top level ;)

**Comment by JoeWoodward** [comment]
👍 Yeah, sorry missed this comment. As Thibault mentioned above.
