### ISSUE TITLE
Save and process all blockchain addresses in lowercase

### ISSUE THREAD

**Issue by mederic-p** [omisego/ewallet#1152]
For now, blockchain addresses are saved in the same format as the input. This means that if an address contains mixed lower and upper letters, it'll be saved as it. We should convert all addresses to lowercase before saving or processing them for more consistency.

**Comment by unnawut** [comment]
You're probably aware of this but noting down for reference that we should validate the mixed-case checksum: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md before we strip of the cases.
