### ISSUE TITLE
Unable to specify DB connection pool size

### ISSUE THREAD

**Issue by cyrilledec** [omisego/ewallet#1175]
**Describe the bug**
DB connection pool size should be configurable using `EWALLET_POOL_SIZE` and `LOCAL_LEDGER_POOL_SIZE` environment variable but changing value of these variables has not effect.
Also default value for `EWALLET_POOL_SIZE` and `LOCAL_LEDGER_POOL_SIZE` are respectively `15` and `5` but in reality on database side we can see double amount of connections (`30` for `ewallet` and `10` for `local_ledger`). May be related to `DB.SharedConnectionPool` ?

**To Reproduce**
1. Start `ewallet` with default DB connection pool size
2. Check the number of connection on DB side
3. Update `EWALLET_POOL_SIZE` and `LOCAL_LEDGER_POOL_SIZE` environment variable
4. Check again the numbers of connection on DB side -> same number of connections

**Expected behavior**
Number of DB connections should match `EWALLET_POOL_SIZE` and `LOCAL_LEDGER_POOL_SIZE` environment variable

**Additional context**
N/A

**Comment by unnawut** [comment]
Thanks for reporting!

> May be related to `DB.SharedConnectionPool` ?

`DB.SharedConnectionPool` is mainly internal to the application. We have a few subapps (subprocesses) connecting to the same database and so we wanted to reuse the same connection pool. That is, we wanted `ActivityLogger`, `EWalletConfig` and `EWalletDB` to all use the same connection pool, rather than starting 15 connections each.

> Also default value for `EWALLET_POOL_SIZE` and `LOCAL_LEDGER_POOL_SIZE` are respectively `15` and `5` but in reality on database side we can see double amount of connections (`30` for `ewallet` and `10` for `local_ledger`). May be related to DB.SharedConnectionPool ?

Could it be that you have 2-instance horizontal scaling setup? The pool is internal to each instance.

**Comment by cyrilledec** [comment]
Thanks for your explanation about `DB.SharedConnectionPool`

For the number of connection I've checked a single instance (docker) of `ewallet` and I can see (using `netstat`) `40` concurrent open connections to the DB server which is : `10` for `local_ledger` and `30` for `ewallet` (double than default value)

```
/ # netstat -an | grep :5432 | wc -l
40
```
all connection from the same process : 

```
/ # ps -ef
PID   USER     TIME  COMMAND
    1 root      0:00 s6-svscan -t0 /var/run/s6/services
   30 root      0:00 foreground  if   /etc/s6/init/init-stage2-redirfd   foreground    if     if      s6-echo      -n      --
   31 root      0:00 s6-supervise s6-fdholderd
   40 root      0:00 foreground  s6-setsid  -gq  --  with-contenv  backtick  -D  0  -n  S6_LOGGING   printcontenv   S6_LOGGING
  168 ewallet  10:21 /app/erts-9.3.3.3/bin/beam.smp -Bd -- -root /app -progname app/releases/1.1.0/ewallet.sh -- -home /app --
  470 ewallet   0:00 [bash]
  474 ewallet   0:00 /app/erts-9.3.3.3/bin/epmd -daemon
  487 ewallet   0:00 erl_child_setup 1048576
  517 ewallet   0:00 inet_gethost 4
  518 ewallet   0:00 inet_gethost 4
  519 ewallet   0:00 inet_gethost 4
  520 root      0:00 sh
  581 root      0:00 ps -ef
```

```
/ # cat /proc/40/net/tcp | grep 1538 | wc -l
40
```
(`1538` is DB port `5432` in hexadecimal)

**Comment by unnawut** [comment]
I looked into the code a bit more based on your provided info. Unfortunately I'm unable to reproduce the issue. 

What I did are these steps:

1. On host machine:
    ```shell
    curl -O -sSL https://raw.githubusercontent.com/omisego/ewallet/master/docker-compose.yml
    curl -O -sSL https://raw.githubusercontent.com/omisego/ewallet/master/docker-gen.sh
    chmod +x docker-gen.sh
    ./docker-gen.sh > docker-compose.override.yml
    ```

2. Initialize the setup (also on host machine)

    ```shell
    docker-compose run --rm ewallet initdb
    docker-compose run --rm ewallet seed
    docker-compose up -d
    ```

3. Access `ewallet` container:
    ```shell
    docker-compose exec ewallet bash
    ```

4. Run your commands inside `ewallet` container:

    ```shell
    bash-4.4# netstat -an | grep :5432 | wc -l
    20
    ```

    ```shell
    bash-4.4# ps -ef
    PID   USER     TIME  COMMAND
        1 root      0:00 s6-svscan -t0 /var/run/s6/services
       30 root      0:00 foreground  if   /etc/s6/init/init-stage2-redirfd   foreground    if     if      s6-echo      -n      --      [s6-init] making user provided files available at /var/run/s6/etc...          foreground      backtick
       31 root      0:00 s6-supervise s6-fdholderd
       40 root      0:00 foreground  s6-setsid  -gq  --  with-contenv  backtick  -D  0  -n  S6_LOGGING   printcontenv   S6_LOGGING    importas  S6_LOGGING  S6_LOGGING  ifelse   s6-test   ${S6_LOGGING}   -eq   2     redirfd   -w   1   /var/ru
      168 ewallet   0:05 /app/erts-10.2.3/bin/beam.smp -Bd -- -root /app -progname app/releases/1.3.1/ewallet.sh -- -home /app -- -noshell -noshell -noinput -boot /app/releases/1.3.1/ewallet -boot_var ERTS_LIB_DIR /app/erts-10.2.3/../lib -pa
      380 ewallet   0:00 [bash]
      384 ewallet   0:00 /app/erts-10.2.3/bin/epmd -daemon
      388 ewallet   0:00 erl_child_setup 1048576
      409 ewallet   0:00 sh -s disksup
      410 ewallet   0:00 /app/lib/os_mon-2.4.7/priv/bin/memsup
      411 ewallet   0:00 /app/lib/os_mon-2.4.7/priv/bin/cpu_sup
      413 ewallet   0:00 inet_gethost 4
      414 ewallet   0:00 inet_gethost 4
      415 root      0:00 bash
      426 root      0:00 ps -ef
    ```

    ```shell
    bash-4.4# cat /proc/40/net/tcp | grep 1538 | wc -l
    20
    ```

**Comment by cyrilledec** [comment]
Sorry I forgot to mention that the deployment has been done via `helm chart` (https://github.com/omisego/charts/tree/master/ewallet) version and using the docker image of `ewallet` tag `v1.1.0`
Same issue on 2 different deployments. I will try to reproduce it on my local `minikube` and share info on how to reproduce it ASAP.

**Comment by cyrilledec** [comment]
I'm able to reproduce the issue on local minikube using `ewallet` docker image `1.1.0`.
Also I saw the following PR : https://github.com/omisego/ewallet/pull/853
I guess I have to use a newer version of `ewallet` (1.2.0)

**Comment by unnawut** [comment]
I can re-confirm your findings that the shared connection pool went in at https://github.com/omisego/ewallet/releases/tag/v1.2.0.

And yes, prior to https://github.com/omisego/ewallet/pull/853, all subapps would be using the [default `pool_size: 10`](https://github.com/elixir-ecto/ecto/blob/v3.0.7/lib/ecto/repo/supervisor.ex#L5) each, hence the behaviour you are seeing. Upgrading to `v1.2.0` would be the most ideal solution.

**Comment by unnawut** [comment]
Thank you for digging into this!
