### ISSUE TITLE
mix seed error

### ISSUE THREAD

**Issue by Alainy** [omisego/ewallet#173]
# Mix seed

Running mix seed caused an Argument error. 

# Environment
* Node v8.11.1
* Yarn v1.6
* Elixir v1.6.5
* Erlang 20

# Steps to reproduce
I installed all dependencies with brew and followed all the steps in [Setting up](https://github.com/omisego/ewallet#setting-up). After pressing Enter to start seeding the following error is shown:
```
** (ArgumentError) argument error
    :erlang.bit_size(%EWalletDB.AuthToken{__meta__: #Ecto.Schema.Metadata<:loaded, "auth_token">, account: #Ecto.Association.NotLoaded<association :account is not loaded>, account_uuid: "d5b1eb7e-1397-4e8e-8531-0b6dfe166438", expired: nil, id: "atk_01cczydqdxtpawt0jxax5k8m5c", inserted_at: ~N[2018-05-08 13:18:04.733672], owner_app: "admin_api", token: "_PXmVfh6jZjZM57bvZ_O339He1VWP-D9r4cgJjrKpPE", updated_at: ~N[2018-05-08 13:18:04.733683], user: #Ecto.Association.NotLoaded<association :user is not loaded>, user_uuid: "35ef600a-8ea2-41ad-a793-e59a5d20afcc", uuid: "e09068c2-444c-4483-8889-51c4930a0103"})
    apps/ewallet/priv/repo/report_minimum.exs:86: (file)
    (elixir) lib/code.ex:629: Code.load_file/2
    apps/ewallet/priv/repo/seeder.exs:160: EWallet.Seeder.call/1
    (elixir) lib/code.ex:677: Code.require_file/2
    (mix) lib/mix/tasks/run.ex:136: Mix.Tasks.Run.run/5
    (mix) lib/mix/tasks/run.ex:76: Mix.Tasks.Run.run/1
    (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
    (mix) lib/mix/task.ex:348: Mix.Task.run_alias/3
    (mix) lib/mix/task.ex:277: Mix.Task.run/2
    (mix) lib/mix/cli.ex:80: Mix.CLI.run_task/2
```

**Comment by unnawut** [comment]
Thank you! This is a valid bug that I've just experienced myself as well. I included the fix as part of #172 but since it's not really related to the PR and people are experiencing it, I'm going to extract the fix into a separate PR.

**Comment by unnawut** [comment]
The fix has been merged to `develop` branch. 

Please try again by pull down the latest `develop` branch and run `mix seed` or `mix seed --sample` depending on your needs.

Again thanks for reporting!

**Comment by Alainy** [comment]
This error returned with the docker setup installation. I will get this error after running `docker exec -it <container-id> mix do seed`.
