### ISSUE TITLE
Minted token create

### ISSUE THREAD

**Issue by Alainy** [omisego/ewallet#177]
# Minted token create request error
Creating minted tokens response returns that the request is bad.  I have tried in swagger, admin panel and go. Even though I am using the default parameters it results in the following response:
```
{
  "version": "1",
  "success": false,
  "data": {
    "object": "error",
    "messages": null,
    "description": "Invalid parameter provided",
    "code": "client:invalid_parameter"
  }
}
```

# Your environment
I am on commit 169bf5c.

# Steps to reproduce
Parameters:
```
{
  "symbol": "BTC",
  "name": "Bitcoin",
  "description": "desc",
  "subunit_to_unit": 100
}
```

**Comment by unnawut** [comment]
Valid bug. Just got the same report on RocketChat yesterday. A fix is on its way. Thanks again for filing the issue!
