### ISSUE TITLE
Mention about Golang  client in project README

### ISSUE THREAD

**Issue by Alainy** [omisego/ewallet#187]
Hey everybody,

This isn't really an issue but I don't know where to share this. I just published a Go SDK for the eWallet and Admin API: https://github.com/Alainy/OmiseGo-Go-SDK

It isn't a finished package yet but I hope it can be of use for someone. Also feedback is welcome!

**Comment by unnawut** [comment]
Thanks! Please give us some time to look into this.

**Comment by sirn** [comment]
We should mention about community SDKs in #253

**Comment by unnawut** [comment]
I'm updating the readme so I'll take care of this.
