### ISSUE TITLE
Drop libsodium in favor for alternatives

### ISSUE THREAD

**Issue by sirn** [omisego/ewallet#232]
Currently we're using libsodium for metadata encryption in the eWallet DB and Local Ledger DB. Unfortunately, as libsodium (via enacl) is a NIF and I couldn't find a way to bundle libsodium along with release, this makes distributing eWallet binaries for supported platforms a bit harder than I'd hope (e.g. no cross compilation, for one thing). 

As libsodium is only used for metadata encryption via Cloak (hopefully not very important) it might more more feasible to switch to AES256-GCM instead. I'd love to hear what you think @thibault @unnawut. Also looping in @fred.

**Comment by T-Dnzt** [comment]
Sounds good to me, I don't see any reason not to switch if it makes it easier to distribute binaries. Let's make it happen!

**Comment by sirn** [comment]
@thibault Oops! 🤦‍♂️ You have my apologize. Very sorry about this.

**Comment by sirn** [comment]
Implemented as of #240
