### ISSUE TITLE
Cannot get ewallet to setup on Ubuntu (any version) using Docker

### ISSUE THREAD

**Issue by atlanticstarr1** [omisego/ewallet#248]
# Subject of the issue
Cannot get ewallet to setup correctly on Ubuntu using Docker or git clone.
Describe your issue here.

git clone https://github.com/omisego/ewallet && cd ./ewallet
$ mix deps.get

The above instructions are not working. I get an error stating * (Mix) The task "archive.check" could not be found.

Also when using the docker image, i keep getting the below error:
23:32:07.935 [error] Postgrex.Protocol (#PID<0.778.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (127.0.0.1:5432): connection refused - :econnrefused

I CAN connect to that port on my local so i don't know why i'm getting the issue.

# Your environment
Ubuntu 17

**Comment by unnawut** [comment]
**1. Git clone & run on your machine:** I'm not sure yet what causes this. Could you run the following commands and let us know the full outputs?

```sh
$ uname -a
$ elixir --version
$ mix help
```

**2. Run the docker image:** The ewallet server depends on a separate postgres database to run. So you'll need to setup a postgres database for the ewallet server to talk to. 

We don't have an official docker-compose file yet, but you can get the idea from here: https://gist.github.com/unnawut/0fcff22d6d191d830dc3350fcc4c8753#file-docker-compose-yml

**Comment by sirn** [comment]
Regarding your second problem, I believe this is due to Docker unable to access local host port from inside the container. In this case, using the IP address from `ip addr show docker0` (in the host machine) should allow the container to connect to local PostgreSQL.

For the first problem, it might be due to version mismatch. Ubuntu 17.10 ship a rather old version of Elixir by default (1.3.3). Our development environment is Debian 9 and Elixir 1.6.5 distribution from [Erlang Solutions](https://www.erlang-solutions.com/resources/download.html).

**Comment by atlanticstarr1** [comment]
Thanks sirn,
Installing the latest version of Elixir did the trick !!!. However, now as i try to log into the  admin panel, i am getting an error "Endpoint not found"
![image](https://user-images.githubusercontent.com/7112049/41512056-d00ddad6-7250-11e8-8b5c-6f440845cacd.png)

I am not running on localhost but on a google virtual machine. Is there a config setting i need to change to reflect that ?

Thanks

**Comment by InoMurko** [comment]
It seems to me that the front-end is out of sync from the API, because the login endpoint in the admin api is /admin.login as in:
`post("/admin.login", AdminAuthController, :login)`

but clicking on the button goes straight to "/login" though.

**Comment by unnawut** [comment]
I'm a bit crammed with other PRs. @jarindr Do you have any idea?

**Comment by jarindr** [comment]
frontend code is out of sync with the api, we changed the name and seems like that version the frontend code still using the old endpoint name.
