### ISSUE TITLE
Improve project README

### ISSUE THREAD

**Issue by sirn** [omisego/ewallet#253]
The current README for the project is a little big overwhelming to get started. I believe the user will benefit greatly if we simplify the README to just topic user will first look for, and link to a more advanced topics in the docs/ directory. 

Here's some example of a project I stumbled upon that has a great README or something we could take hint from:

* [FoundationDB](https://github.com/apple/foundationdb) — very concise and clear, and has everything I want to know about the project at a glance. I especially like the "Compiling from source" which is loosely written, but very easy to follow.
* [Milksnake](https://github.com/getsentry/milksnake) — this is organized in a "Why", "What", and "How" which I like. I think making the heading a question make it easy to focus on explaining a single thing, and it coincides nicely with the user's expectation of the README in the first place, e.g. if we have "How to install?" section for when user look for how to install. 
* [Re-frame](https://github.com/Day8/re-frame) — a bit different from what I'm proposing for README, and it's more of an article, but the framework require full understanding of the concept and the author did a great job putting all pieces together that you'd be able to use it immediately after finished reading the README.

Feel free to add more examples.

**Comment by T-Dnzt** [comment]
Agreed, definitely planning to do this before 1.0 release. If you want to tackle it, be my guest :D

**Comment by unnawut** [comment]
Will review those examples later. Meanwhile, these are some of the main README feedbacks I got from those who're looking to integrate our SDKs:

- Information overload for someone to start by reading the readme, with too many options and jumps. --> Consider make the README one straight flow without branching different options, and put the options as separate pages?
- They got confused in the "Getting Started" section. Unclear whether Docker, Goban and the rest are continuous or they are mutual options. --> Same solution as point above.
- ENVs are not too clear of which ones are required for which environment. E.g. `EWALLET_SECRET_KEY` is required for `prod` but not `dev`. --> List the ENVs along with the requirements in each environment?

**Comment by jarindr** [comment]
Need to update README for admin panel too.
