### ISSUE TITLE
Implement advanced filtering for Admin API

### ISSUE THREAD

**Issue by T-Dnzt** [omisego/ewallet#334]
Currently, it isn't possible to do proper advanced filtering using `search_term` and `search_terms`. An advanced filtering system needs to be implemented (potentially using a new field, `filters`?) that would contain a list of `AND`/`OR` predicates.

The filtering system should allow association filtering up to one level (e.g. from `/wallet.all`, I should be able to specify `account.name = something`. Different comparison mechanism should be supported: `greater`, `equal`, etc.).

Open to suggestions for Elixir libraries that could handle this.

**Comment by unnawut** [comment]
Checked a few libraries. These are the potentials:
- [rcdilorenzo/filtrex](https://github.com/rcdilorenzo/filtrex) - Most complex but also seems the most powerful. Operators like `AND`, `OR`, `>=`, `<=`, `!=` are built-in. Also has built-in input validators.
- [omohokcoj/filterable](https://github.com/omohokcoj/filterable) - Less complex, less powerful. No built-in operators. Only a single contributor.
- [DockYard/inquisitor](https://github.com/DockYard/inquisitor) - Simplest, least powerful. Could easily do without the library.

But actually, I'm inclined towards building our own basic `EWallet.Web.QueryParamFilter` whose the APIs are as simple as [DockYard/inquisitor](https://github.com/DockYard/inquisitor) that doesn't have custom conventions or macros. Then add our own custom filters with inspiration from [rcdilorenzo/filtrex](https://github.com/rcdilorenzo/filtrex).

**Comment by unnawut** [comment]
The format we're going with:

```js
POST /transaction.all
{
  "filters": [
    {
      "field": "created_at",
      "comparator": "gte",
      "value": "2018-08-01"
    },
    {
      "field": "created_at",
      "comparator": "lte",
      "value": "2018-08-31"
    }
  ],
  "filter_matching": "all"
}
```
