### ISSUE TITLE
Allow the eWallet to work without integration

### ISSUE THREAD

**Issue by T-Dnzt** [omisego/ewallet#357]
Currently, the eWallet cannot be used as a stand-alone with only mobile applications using it (currently, it is needed for a provider to create an application to store users, etc.)

This feature is needed for the sample Coffee shop application we're going to be working on.

It involves:

- A merchant app, where an administrator can login (by entering email/password). From this application, a logged-in admin can then proceed to top-up or purchase on behalf of a user by scanning a user's identity QR code. This application should automatically logout admins unless they specified a "Remember Me" button, hence the need to add Face ID / Touch ID.
- A user app, where a user should be able to sign up and login (all through the eWallet API, `/signup` is currently missing. The user can then see his balances or generate his identity QR code.

Tasks:

- [ ] Ensure the differentiation field between admins and users is only `provider_user_id`
-  [ ] Add `/user.signup` endpoint in client API, which will only proceed a request if `ALLOW_USER_REGISTRATION` is set to `true` (defaults to `false`)
- [ ] Add `/user.login` endpoint in client API (which follows the same rules as above, depending on `ALLOW_USER_REGISTRATION`

**Comment by unnawut** [comment]
If this eWallet becomes standalone, the end users won't even have `provider_user_id`.

Need to figure out if `provider_user_id` should be generated, or find another differentiator.
