### ISSUE TITLE
Database Migration Error

### ISSUE THREAD

**Issue by atlanticstarr1** [omisego/ewallet#392]
# Subject of the issue
Database Migrations not running on bare-bones build.
Describe your issue here.

# Your environment
Ubuntu 18
Tell us where this issue occurred.
1.4 Migrate the databases (From the ReadMe manual)
# Steps to reproduce
Run mix do ecto.create, ecto.migrate
Tell us how to reproduce this issue.
mix do ecto.create, ecto.migrate
# Expected behavior
Databases should be created
Tell us what should happen.
Databases should be created.
# Actual behavior
23:16:12.677 [error] GenServer #PID<0.724.0> terminating
** (RuntimeError) Connect raised a KeyError error. The exception details are hidden, as
they may contain sensitive data such as database credentials.

    (elixir) lib/keyword.ex:377: Keyword.fetch!/2
    (postgrex) lib/postgrex/protocol.ex:610: Postgrex.Protocol.auth_md5/4
    (postgrex) lib/postgrex/protocol.ex:504: Postgrex.Protocol.handshake/2
    (db_connection) lib/db_connection/connection.ex:135: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for LocalLedgerDB.Repo couldn't be created: an exception was raised:
    ** (RuntimeError) Connect raised a KeyError error. The exception details are hidden, as
they may contain sensitive data such as database credentials.

        (elixir) lib/keyword.ex:377: Keyword.fetch!/2
        (postgrex) lib/postgrex/protocol.ex:610: Postgrex.Protocol.auth_md5/4
        (postgrex) lib/postgrex/protocol.ex:504: Postgrex.Protocol.handshake/2
        (db_connection) lib/db_connection/connection.ex:135: DBConnection.Connection.connect/2
        (connection) lib/connection.ex:622: Connection.enter_connect/5
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Tell us what happens instead.

**Comment by unnawut** [comment]
Closing down for now. Feel free to re-open if you still experience this issue!
