### ISSUE TITLE
Admin API User endpoints inconsistency

### ISSUE THREAD

**Issue by Alainy** [omisego/ewallet#402]
The endpoints `/user.get`, `/user.get_wallets` and `/user.get_transactions` all use the parameter `id` or `provider_user_id` in the request body to identify a user. But the endpoint `/user.get_transaction_consumptions` uses the parameter `user_id`. Is there a reason behind this inconsistency?

**Comment by T-Dnzt** [comment]
That's an inconsistency bug, indeed 😅 Thanks for reporting it, we're gonna fix it.
