### ISSUE TITLE
Upgrade to Elixir 1.8

### ISSUE THREAD

**Issue by T-Dnzt** [omisego/ewallet#489]

**Comment by unnawut** [comment]
Note that Elixir 1.8 [should be out next Janurary](http://blog.plataformatec.com.br/2018/11/whats-new-in-elixir-nov-18/).

**Comment by unnawut** [comment]
Resurrecting it for 1.8.0 in v1.2

**Comment by sirn** [comment]
FYI since we're using bundled ERTS in release now, just upgrading Erlang/Elixir in https://github.com/omisego-images/docker-ewallet should be suffice.
