### ISSUE TITLE
Possible Bypass For URL Validator

### ISSUE THREAD

**Issue by jpopxfile** [omisego/ewallet#583]
# Subject of the issue
In https://github.com/omisego/ewallet/blob/master/docs/setup/advanced/env.md, the following documentation is written for the REDIRECT_URL_PREFIXES: 

>External redirects
Some features such as email verification allows redirects to URIs external to the eWallet. For security reasons we do not allow redirects to arbitary URIs, unless the prefix is whitelisted.

>REDIRECT_URL_PREFIXES: A comma-separated list of prefixes that are allowed to be redirected to. For example, REDIRECT_URL_PREFIXES=https://example.com,pos-client://example.com allows redirects to https://example.com/some_url and pos-client://example.com/some_deep_linked_url.

By setting the url as https://example.com, there are some possible bypasses

# Your environment

https://github.com/omisego/ewallet/blob/master/apps/ewallet/lib/ewallet/web/url_validator.ex

# Steps to reproduce

I have used the code from url_validator.ex (with some hard coded urls for visibility)

```
defmodule UrlValidator do
  @moduledoc """
  This module validates a url.
  """

  @doc """
  Checks that the given url is allowed as a redirect url.
  """
  def allowed_redirect_url?(url) do
    base_url = "https://example.com"
    prefixes = ["https://google.com", "https://example2.com"]
    allowed = [base_url | prefixes]

    Enum.any?(allowed, fn prefix -> String.starts_with?(url, prefix) end)
  end
end

IO.puts UrlValidator.allowed_redirect_url?("https://example.com.notexample.com")
IO.puts UrlValidator.allowed_redirect_url?("https://example.com@notexample.com")
IO.puts UrlValidator.allowed_redirect_url?("https://example.comnotexample.com")
```

This produces the following output
```
$elixir main.exs
true
true
true
```

# Expected behavior

None of the 3 inputs are of the host example.com. Thus, it should return false.

# Actual behavior

True is returned.

# Mitigation suggestions
1) Make sure to state in the documentation that you need to end the whitelisted REDIRECT_URL_PREFIXES with a "/" character.

2) Instead of checking the whole path, check the host domain name against a whitelist.

**Comment by unnawut** [comment]
Good catch! Looks valid to me.

**Comment by jpopxfile** [comment]
On an unrelated note, was wondering if OmiseGo has some sort of (bug) bounty program for pointing out security related issues. Have been working with Fred on some on the Omise security issues, so would be cool if the same thing exists for OmiseGo too

**Comment by unnawut** [comment]
That is in the plan but I'm not sure when it will be up. Maybe @T-Dnzt has more details on that.

**Comment by unnawut** [comment]
Expanding on @jpopxfile's suggestions a bit, maybe we could add a stricter validation like this?

Given `REDIRECT_URL_PREFIXES=https://example.com/,pos-client://example.com` (note that the former has a trailing slash):

1. Trim trailing slashes (if any) from each of the `REDIRECT_URL_PREFIXES`.
2. Allow if either:
    - The given URL matches the allowed URLs exactly, i.e. `^https://example.com$` and `^pos-client://example.com$`
    - The given URL starts with the allowed URLs with "/" appended, i.e. `^https://example.com/.*$` and `^pos-client://example.com/.*$`.

This way we don't need to rely on users providing the trailing slashes or not, while also avoiding complex URL parsing for protocols and domains.

Thoughts? @T-Dnzt @jpopxfile

**Comment by jpopxfile** [comment]
Looks ok to me, but do note that we need to the escape the dots in the regular expression to \. or [.]

Otherwise, if the whitelist is a subdomain:
`^https://xxx.example.com$`
This pattern would match for https://xxxaexample.com

**Comment by unnawut** [comment]
👍 Yup you're right. Apologies for my pseudo regex.

**Comment by jpopxfile** [comment]
Took a look at the PR and I can't find any bypass for this enhancement.
