### ISSUE TITLE
Test upgrade path from 1.0 to 1.1

### ISSUE THREAD

**Issue by T-Dnzt** [omisego/ewallet#684]
Also, write up any needed documentation about the upgrade.

**Comment by unnawut** [comment]
Remaining:
- [ ] Convert `mix omg.migrate.settings` to a release task
- [ ] Convert `mix omg.seed` to a release task

**Comment by unnawut** [comment]
In addition to #733, I'll try run with a DB snapshot from a v1.0 instance.

**Comment by unnawut** [comment]
Looking good with all v1.0 instances we have access to. 🎉

**Comment by unnawut** [comment]
Migrations tested on all available v1.0 instances. Setup docs ran through. All looking good.
