### ISSUE TITLE
Add blockchain settings

### ISSUE THREAD

**Issue by T-Dnzt** [omisego/ewallet#686]
The following settings should be added to the eWallet for the blockchain features. We might want to add those settings a label such as `administrator`-only to show off their importance (and the associated risks).

- `enable_blockchain_integration`:
- hot wallet address
- confirmations_count

**Comment by sirn** [comment]
Do we actually need `enable_blockchain_integration`? I think we can just have `blockchain_adapter` set to `nil`. Also I kinda think `blockchain_primary_node` is something adapter-specific and probably should be included in adapter settings itself… e.g.

```
blockchain_adapter: [:geth, {node: :rinkeby}]
```

🤔 ?

**Comment by T-Dnzt** [comment]
I agree with the first point. About storing the node in the `blockchain_adapter` setting - the thing is I'd love if those settings could actually be changed through the admin panel (if `ADVANCED_MODE` or something is set in the ENV, so we can set it on our eWallets), so we'd probably need to use a `JSON` like:

```
blockchain_configuration: {
  adapter: "geth",
  node: "rinkeby"
}
```

This is actually nice because we could just dump the whole configuration to the blockchain adapter and let it deal with parsing it and getting what it needs out of it 🤔

**Comment by sirn** [comment]
Yeah, having `blockchain_configuration` works for me too. I posted that and remembered about having to convert to JSON, so definitely this one works better.

**Comment by unnawut** [comment]
Can the network be changed after it is set? E.g. from testnet <-> mainnet, etc.

Handling the network change will be really hard / break completely with the totally different set of data.

On top of my mind, maybe `blockchain_configuration` could have `:adapter`, `:node_type` and `:network` and are immutable.

Then a separate config `blockchain_primary_node` for the node location? But this still doesn't prevent users from inputting a node from a different network.

**Comment by T-Dnzt** [comment]
Yeah, we could keep it in another setting. If they pick a node from another network, it's not really our problem. Once in service, the first setting (`blockchain_configuration`) should be immutable.

**Comment by unnawut** [comment]
Collected settings by application...

**`:eth_geth_adapter`**
- `ethereumex.url` (env var: `JSON_RPC_GETH_NODE_URL`, should be configurable)
- `ethereumex.client_type` (hardcode to `:http`, no need to expose)

**`:ewallet_db`**
- `:blockchain_adapter` (to remove, not used anywhere)
- `:rootchain_identifier` (no need to expose, just move into `:eth_blockchain` or similar)
- `:childchain_identifier` (no need to expose, just move into `:eth_blockchain` or similar)

**`:eth_blockchain`**
- `:chain_id` (env var: `ROOTCHAIN_CHAIN_ID`, should be configurable)
- `:transaction_poll_interval` (this is for polling new info by transaction hash, should be configurable)
- `:default_gas_price` (should be configurable, or maybe change to `:max_gas_price`?)

**`:ewallet`**
- `:deposit_pooling_interval` (should be configurable)
- `AddressTracker.@blk_syncing_save_interval` (should be configurable)
- `AddressTracker.@blk_syncing_polling_interval` (doesn't seem to be used, to remove)
- `AddressTracker.@syncing_interval` (used when the system syncs at startup, should be configurable)
- `AddressTracker.@polling_interval` (used after the system is up to date with the latest block number, should be configurable)

**Comment by unnawut** [comment]
*`eth_omisego_adapter`*
- [ ] `:contract_address` (should be configurable)
- [ ] `:childchain_url` (should be configurable)
- [ ] `:watcher_url` (should be configurable)

**Comment by unnawut** [comment]
- [ ] `AddressTracker` and `DepositWalletPoolingTracker` should resume polling when interval is configured from `0` to `> 0` without application restart
