### ISSUE TITLE
Update ex_doc to 1.9.3

### ISSUE THREAD

**Issue by jpopxfile** [omisego/ewallet#688]
# Subject of the issue
Compilation error in ex_doc dependency for version 1.9.1.

# Your environment
Elixir 1.9.0

# Steps to reproduce

```
$  mix do ecto.create, ecto.migrate
[...]
== Compilation error in file lib/ex_doc/formatter/html/autolink.ex ==
** (CompileError) Elixir.ExDoc.Formatter.HTML.Autolink: function split_function/1+2:
  Internal consistency check failed - please report this bug.
  Instruction: {func_info,{atom,'Elixir.ExDoc.Formatter.HTML.Autolink'},
                          {atom,split_function},
                          1}
  Error:       {unexpected_stack_frame,undecided}:

    (stdlib) lists.erl:1338: :lists.foreach/2
    (elixir) src/elixir_erl_compiler.erl:12: anonymous fn/3 in :elixir_erl_compiler.spawn/2
    (elixir) lib/kernel/parallel_compiler.ex:206: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
could not compile dependency :ex_doc, "mix compile" failed. You can recompile this dependency with "mix deps.compile ex_doc", update it with "mix deps.update ex_doc" or clean it with "mix deps.clean ex_doc"
```

# Expected behavior
Dependencies should compile without any error.

# Actual behavior
There is a compliation error, which is fixed by updating ex_doc's version to 1.9.3 in mix.lock.

Not sure if this affects other elixir versions, but if upgrading to 1.9.3 does not have any side effects, the dependency version for ex_doc should be updated.

**Comment by jarindr** [comment]
thank you for reporting ! let us look into it and get back to you.

**Comment by unnawut** [comment]
@jpopxfile Could you confirm again which elixir version are you on? The latest release right now is [v1.8.0](https://github.com/elixir-lang/elixir/releases/tag/v1.8.0) so Elixir 1.9.0 is probably a typo. 

Also feel free to submit a pull request if you'd like. Thanks!

**Comment by jpopxfile** [comment]
I'm on 1.9.0 (dev), compiled it from source's master branch.
I guess I should be downgrading to v1.8.0?

**Comment by unnawut** [comment]
Yes please. Although embarrassing to say, we're still on Elixir 1.6.

Upgrade to Elixir 1.8 is coming with #489 targeted for ewallet v1.2.

**Comment by unnawut** [comment]
We're now on :ex_doc 0.19.3 🎉
