### ISSUE TITLE
Ethereum account generation in eWallet

### ISSUE THREAD

**Issue by T-Dnzt** [omisego/ewallet#689]
This issue consists in implementing a module that will generate a new Ethereum account and all the needed helper functions. From it, we should be able to get a private key, a public key and an address. This will later be used for hot wallet generation.

**Comment by unnawut** [comment]
Question: Does it generate a private key directly or should it be a mnemonic phrase?

**Comment by T-Dnzt** [comment]
But can't we just re-generate new private / public when needed? I don't see the usefulness of using a mnemonic phrase.

**Comment by unnawut** [comment]
Ok so referring to #690 that private keys will be encrypted & stored in the database, with the single encryption key stored in environment variable. This should solve the trouble having to manage a lot of private keys.

**Comment by T-Dnzt** [comment]
A library we might want to explore: https://github.com/izelnakri/eth

**Comment by unnawut** [comment]
Looks like https://github.com/izelnakri/eth  is mainly a wrapper over https://github.com/mana-ethereum/ethereumex that casts and maps values. Very handy!

But given that it's been inactive since May 2018, we might want to roll our own that uses https://github.com/mana-ethereum/ethereumex directly.

**Comment by unnawut** [comment]
Closed by #807 and #863
