### ISSUE TITLE
Ethereum Node Communication (with Geth adapter)

### ISSUE THREAD

**Issue by T-Dnzt** [omisego/ewallet#693]
Our original implementation will only support Geth, but it should be done in a way that allows the switch to other types of nodes later on. Therefore, adapter modules needs to be implemented, starting with the Geth one.

We should only rely on the `JSON-RPC` API, because, while the eWallet will ship with an Ethereum node (and could potentially use the IPC API), it is actually possible to connect to remote nodes as well (as this will be the case at first).

 __No Ethereum accounts__ should be generated/stored in Geth.

**Comment by unnawut** [comment]
Suggesting the the adapter aligns its API with https://github.com/ethereum/wiki/wiki/JSON-RPC#json-rpc-api?
