### ISSUE TITLE
Update Token and add ETH generating module

### ISSUE THREAD

**Issue by T-Dnzt** [omisego/ewallet#695]
Requires #693

The ETH token should automatically be added when the blockchain adapter is enabled and set to Ethereum. 

1. First, we need to give the capacity to our internal tokens to become blockchain tokens and contains blockchain details (such as the smart contract address for ERC-20 tokens). 
2. Each blockchain adapter will need a booting function to prepare the eWallet to support that blockchain. In Ethereum's case, this would involve generating the ETH token.

- [ ] Turn internal tokens into blockchain tokens.
- [ ] Add setup function to the Ethereum adapter we've built.
- [ ] Generate the ETH token if not already present.

**Comment by unnawut** [comment]
This seems quite dependent on the design of the blockchain adapter.

Moving back to To Do and focusing on importing existing blockchain tokens instead, since this should be more generic to any kind of adapter design.
