### ISSUE TITLE
Ethereum Multi-Node Interface

### ISSUE THREAD

**Issue by T-Dnzt** [omisego/ewallet#696]
To know what's going on in the blockchain we're connected to, we need to handle the events coming from it, and process them.

This needs to be built as an external service that can be integrated and run inside an umbrella app if wanted. It should connect to Geth + Parity in the first iteration and forward the events to whoever subscribe to get them.

The idea would be to offer the events through pub/sub interfaces (either directly in Elixir, or through websockets). This will be used by the blockchain team as well.

**Comment by unnawut** [comment]
Refer to: https://github.com/ethereum/go-ethereum/wiki/RPC-PUB-SUB

**Comment by unnawut** [comment]
Closing this in favor of #1027 and tasks in https://github.com/omisego/potterhat/issues.
