### ISSUE TITLE
Update transactions to show Ethereum ones

### ISSUE THREAD

**Issue by T-Dnzt** [omisego/ewallet#714]

**Comment by unnawut** [comment]
Some thoughts on top of my head:

- It should be able to show local ledger & blockchain txns seamlessly within the same table.
- Question: Do we need to consider how many block confirmations before showing?
- How much of blockchain data it needs to show? E.g.
  - Gas cost / transaction cost
  - Block height
  - How/which to display: destination contract, destination address, both?
  - How to show if to or from is not in our database (i.e. only has blockchain address, no account, user or local wallet address)?
