### ISSUE TITLE
Admin panel & Swagger UI assets could not be loaded

### ISSUE THREAD

**Issue by unnawut** [omisego/ewallet#756]
# Subject of the issue

Admin panel & Swagger UI assets are not being served on the latest docker image of `omisego/ewallet:latest`.

# Your environment

- MacOS 10.13.6
- Docker version 18.09.1, build 4c52b90
- docker-compose version 1.23.2, build 1110ad01
- Docker image: omisego/ewallet, latest, 21ef67e9fd36, 8 hours ago, 241MB

# Steps to reproduce

Run `docker-compose up -d` following the setup instructions in the README.md.

Then try to access http://localhost:4000/admin, http://localhost:4000/api/admin/docs.ui and http://localhost:4000/api/client/docs.ui

# Expected behavior

- http://localhost:4000/admin displays the admin panel front end successfully.
- http://localhost:4000/api/admin/docs.ui renders the Swagger UI for Admin API.
- http://localhost:4000/api/client/docs.ui renders the Swagger UI for Client API.

# Actual behavior

- http://localhost:4000/admin displays:
    > The assets are not available. If you think this is incorrect, please make sure that the front-end assets have been built.
- http://localhost:4000/api/admin/docs.ui returns the page but assets are all 404
- http://localhost:4000/api/client/docs.ui returns the page but assets are all 404

**Comment by sirn** [comment]
My guess is that our `:dist_path` is defined in `config.exs` using `File.expand` which means the value of it will be compiled when we run distillery release. Changing to use MFA function probably fix it.

**Comment by sirn** [comment]
Actually [SpecialForms](
https://hexdocs.pm/elixir/Kernel.SpecialForms.html) are likely expanded at compile time rather than runtime, so I guess we have to change the function to not rely on `__DIR__` as well. 🤔

**Comment by unnawut** [comment]
Closes with #763
