### ISSUE TITLE
Missing port binding in docker-compose.yml

### ISSUE THREAD

**Issue by unnawut** [omisego/ewallet#757]
# Subject of the issue

The docker-compose file does not bind the backend port, i.e. `4000`.

# Your environment

- MacOS 10.13.6
- Docker version 18.09.1, build 4c52b90
- docker-compose version 1.23.2, build 1110ad01
- Docker image: omisego/ewallet, latest, 21ef67e9fd36, 8 hours ago, 241MB

# Steps to reproduce

Follow the setup instructions in `README.md`. Then try to access `http://localhost:4000`.

# Expected behavior

`http://localhost:4000` should return the JSON status response.

# Actual behavior

`http://localhost:4000` returns ERR_CONNECTION_REFUSED

**Comment by reyeshh** [comment]
http://localhost:4000/admin returns the following:
The assets are not available. If you think this is incorrect,
please make sure that the front-end assets have been built.

**Comment by sirn** [comment]
We're working for a fix for this at #763. It should land sometimes
today (in UTC+7 timezone). Sorry for the trouble!

**Comment by sirn** [comment]
The issue is fixed in `omisego/ewallet:1.1-dev` image, it should be fixed in `latest` as soon as we sync v1.1 back to master later today.
