### ISSUE TITLE
Migrate BALANCE_CACHING_FREQUENCY to EWalletConfig

### ISSUE THREAD

**Issue by sirn** [omisego/ewallet#767]
Right now `BALANCE_CACHING_FREQUENCY` still use env var.

**Comment by unnawut** [comment]
Having it in `v1.1.0` would remove the user's burden of having to run `config --migrate` once more.

**Comment by unnawut** [comment]
Nevermind. Working on it now. Should be quick.

**Comment by unnawut** [comment]
Closed with #777

**Comment by unnawut** [comment]
14-hour quick 😅
