### ISSUE TITLE
README.md downloads the unstable omisego/ewallet:latest image

### ISSUE THREAD

**Issue by unnawut** [omisego/ewallet#769]
The [`docker-compose.yml`](https://raw.githubusercontent.com/omisego/ewallet/master/docker-compose.yml) and [`docker-compose.override.yml`](https://raw.githubusercontent.com/omisego/ewallet/master/docker-gen.sh) mentioned in README.md pulls down `omisego/ewallet:latest` which is from the tip of master and is unstable.

The README.md should refer to the latest stable docker image.

**Comment by sirn** [comment]
Unfortunately the current `:stable` is still using the old `MIX_ENV=prod
mix omg.server` so the rest of instructions (in general) won't work. I
agree we should recommend people to use `:stable` once 1.1 is released though.
