### ISSUE TITLE
Remove 5-association limit from MatchParser

### ISSUE THREAD

**Issue by unnawut** [omisego/ewallet#783]
Since now we're now on Ecto 3 and [[Ecto.Query] Allow joins in queries to be named via :as and allow named binding](https://github.com/elixir-ecto/ecto/blob/master/CHANGELOG.md). We can now get rid of the clunky [`MatchAllQuery`](https://github.com/omisego/ewallet/blob/master/apps/ewallet/lib/ewallet/web/filters/match_all_query.ex) and [`MatchAnyQuery`](https://github.com/omisego/ewallet/blob/master/apps/ewallet/lib/ewallet/web/filters/match_any_query.ex) workarounds.

Thanks to @jarindr for bringing this up.

**Comment by enyan94** [comment]
I've been successful in implementing this feature in that all but one of the related tests are successful. 
Over 5 reference associations now works. The problem I'm facing is that Named Binding in Ecto requires the ":as" name to be a compile time atom. This results in hard-coding the named bindings, which adds a lot of baggage. 

Creating associations with named bindings.
`
              :tokens ->
                queryable = join(queryable, :left, [q], assoc in assoc(q, ^field), as: :tokens)
                {queryable}
`

Adding a where clause to a query:
`  
defp tokens_assoc(current_query, field, subfield, nil, comparator, nil = value) do
    case comparator do
      "eq" -> from [q, tokens: a] in current_query, where: is_nil(field(a, ^subfield))
      "neq" -> from [q, tokens: a] in current_query, where: not is_nil(field(a, ^subfield))
      _ -> {:error, :comparator_not_supported, field: field, comparator: comparator, value: value}
    end
  end

  defp tokens_assoc(current_query, field, subfield, nil, comparator, value) do
    case comparator do
      "eq" -> from [q, tokens: a] in current_query, where: field(a, ^subfield) == ^value
      "neq" -> from [q, tokens: a] in current_query, where: field(a, ^subfield) != ^value
      "gt" -> from [q, tokens: a] in current_query, where: field(a, ^subfield) > ^value
      "gte" -> from [q, tokens: a] in current_query, where: field(a, ^subfield) >= ^value
      "lt" -> from [q, tokens: a] in current_query, where: field(a, ^subfield) < ^value
      "lte" -> from [q, tokens: a] in current_query, where: field(a, ^subfield) <= ^value
      "contains" -> from [q, tokens: a] in current_query, where: ilike(field(a, ^subfield), ^"%#{value}%")
      "starts_with" -> from [q, tokens: a] in current_query, where: ilike(field(a, ^subfield), ^"#{value}%")
      _ -> {:error, :comparator_not_supported, field: field, comparator: comparator, value: value}
    end
  end
`

As you can see in the example above, one association, "tokens", takes up quite a few lines of code. The schema has over 50 associations, making the match_all_query.ex and match_any_query.ex files from ~250 lines of code to over 1000. 

Maybe there's something that I am missing?

**Comment by unnawut** [comment]
Is the reason for needing hard-coded namebinding because you need the form `from [q, tokens: a]`?

Would `from [q, {^atom_field, a}]`, where `atom_field` is passed into the function work?

**Comment by enyan94** [comment]
> Is the reason for needing hard-coded namebinding because you need the form `from [q, tokens: a]`?

To a degree, yes. I needed some way to reference the named bindings in order to use it.

> Would` from [q, {^atom_field, a}]`, where `atom_field` is passed into the function work?

That didn't work either, but I found a [solution](https://stackoverflow.com/a/54491195/11157034). It's quite elegant and reduces all the baggage. It relies on an internal implementation so it is subject to change though. 

Still requires atoms but removes all the clutter.

```elixir
  def do_filter_assoc(current_query, field, subfield, nil, comparator, value) do

    # TODO add remaining associations
    position =
      case field do
        :wallets -> named_binding_position(current_query, :walelts)
        :tokens -> named_binding_position(current_query, :tokens)
        :keys -> named_binding_position(current_query, :keys)
        ...
      end

    # add where clause to association matching "position"
    add_to_query(current_query, field, subfield, nil, comparator, value, position)

  end

  def named_binding_position(query, binding) do
    Map.get(query.aliases, binding) #internal implementaiton
  end

  defp add_to_query(current_query, field, subfield, nil, comparator, value, position) do
    case comparator do
      "eq" -> current_query |> where([{a, position}], field(a, ^subfield) == ^value)
      "neq" -> current_query |> where([{a, position}], field(a, ^subfield) != ^value)
      "gt" -> current_query |> where([{a, position}], field(a, ^subfield) > ^value)
      "gte" -> current_query |> where([{a, position}], field(a, ^subfield) >= ^value)
      "lt" -> current_query |> where([{a, position}], field(a, ^subfield) < ^value)
      "lte" -> current_query |> where([{a, position}], field(a, ^subfield) <= ^value)
      "contains" -> current_query |> where([{a, position}], ilike(field(a, ^subfield), ^"%#{value}%"))
      "starts_with" -> current_query |> where([{a, position}], ilike(field(a, ^subfield), ^"#{value}%"))
      _ -> {:error, :comparator_not_supported, field: field, comparator: comparator, value: value}
    end
  end
```

As of Ecto 3.0, it seems like named bindings will always require compile time atoms to be hard coded.

**Comment by enyan94** [comment]
One more issue I ran into. What's the intended behavior of combining match_all with match_any?

The current implementation of combining a match_all with match_any looks like this:
`
#Ecto.Query<from t0 in EWalletDB.Transaction,
 where: t0.status == ^"confirmed" and (t0.type == ^"internal" and ^true),
 where: t0.status == ^"confirmed" or (t0.type == ^"internal" or ^false),
 distinct: true>
`

My changes will look like this:
`
      Ecto.Query<from t0 in EWalletDB.Transaction, where: t0.type == ^"internal",
       where: t0.status == ^"confirmed", or_where: t0.type == ^"internal",
       or_where: t0.status == ^"confirmed", distinct: true>
`

This yields different results and I'm wondering whether the former was intentional, or was it a side effect of using dynamic queries.

**Comment by unnawut** [comment]
The `and ^true` and `or ^false` are there due to dynamic query building. Your former code example is equivalent to the following:

```elixir
Ecto.Query<from t0 in EWalletDB.Transaction, 
  where: t0.status == ^"confirmed" and t0.type == ^"internal",
  where: t0.status == ^"confirmed" or t0.type == ^"internal",
  distinct: true>
```

which your result is still a little different I think? 🤔

**Comment by unnawut** [comment]
Thank you @enyan94 !
