### ISSUE TITLE
Config migrate command should not update config if it hasn’t been changed

### ISSUE THREAD

**Issue by sirn** [omisego/ewallet#798]
Currently, running `bin/ewallet config -m -y` repeatly will spam activity logs. We should check that the value has actually been updated before writing changes, so we can run `config -m` as part of automatic migration.

In official Helm chart for `omisego/ewallet:1.1.0` we currently run this command on every deploy to migrate environment variable user may have already set in their Kubernetes Pods to the newer configuration to ensure uninterrupted usage. However, we cannot say only run migrate when upgrading from 1.0.0 to 1.1.0… so we have to run it on every deploy.

**Comment by sirn** [comment]
@unnawut can you take this one? This should be in `master` so that our staging won’t have its Activity Logs spammed by migration.

**Comment by unnawut** [comment]
Github why you don't close issues linked with close keywords these days? 💢

**Comment by sirn** [comment]
Because you didn’t merge to master.

**Comment by unnawut** [comment]
Aha!
