### ISSUE TITLE
Handle end user reset password in eWallet view

### ISSUE THREAD

**Issue by T-Dnzt** [omisego/ewallet#864]

**Comment by T-Dnzt** [comment]
Currently, end users will only be able to reset their passwords by clicking on the email on their phones. Doing it from a computer will fail to open the deep-link redirect_url set in the process by the mobile clients.

This issue is about fixing this problem by adding a page to the eWallet OR the admin panel to handle end users forgetting their passwords and wanting to reset through a web interface.

**Comment by mederic-p** [comment]
(see with me for more detail)
