### ISSUE TITLE
钱包什么时候集成区块链功能？

### ISSUE THREAD

**Issue by williamzhangzhang** [omisego/ewallet#902]
# Subject of the issue

Describe your issue here.

# Your environment

Tell us where this issue occurred.

# Steps to reproduce

Tell us how to reproduce this issue.

# Expected behavior

Tell us what should happen.

# Actual behavior

Tell us what happens instead.

**Comment by unnawut** [comment]
Hi. Unfortunately we are unable to give a specific date but work is in progress. Feel free to follow our progress at https://github.com/omisego/ewallet/issues?q=is%3Aopen+is%3Aissue+label%3A%22flag%2Fethereum+integration%22 or https://github.com/buildOMG/tracker/issues/48

**Comment by purplieee** [comment]
优盾钱包基于区块链技术，是行业领先的钱包，使用感还不错
