### ISSUE TITLE
/minted_token.all

### ISSUE THREAD

**Issue by kartsims** [omisego/ewallet#93]
# Subject of the issue

Can't retrieve the full list of tokens.

# Your environment

I am on a fresh Vagrant install, prepared using the `goban` repo.

# Steps to reproduce

- Create a fresh environment (I used `mix seed --sample`) and launch the server
- Create a new token using `/minted-token.create`
- Save the token ID 
- Call `/minted_token.get` on that token ID -> the token data is displayed
- Call `/minted-token.all` -> no data

This is the full JSON response I get from `.all` endpoint :

```
{
  "version": "1",
  "success": true,
  "data": {
    "pagination": {
      "per_page": 10,
      "is_last_page": true,
      "is_first_page": true,
      "current_page": 1
    },
    "object": "list",
    "data": []
  }
}
```

And this is the response I got from `.get` endpoint :

```
{
  "version": "1",
  "success": true,
  "data": {
    "updated_at": "2018-02-28T23:10:13.527129Z",
    "symbol": "SIMSIM",
    "subunit_to_unit": 100,
    "object": "minted_token",
    "name": "Simcoinzzz",
    "id": "SIMSIM:330acf3a-f46a-4dd8-b642-4c246d02da26",
    "created_at": "2018-02-28T23:10:13.527117Z"
  }
}
```

All tests have been done through Swagger only.

# Expected behavior

The token list should not be empty.

# Actual behavior

No token is available in that list.

**Comment by kartsims** [comment]
The `mix seed` output Markdown is actually very different from the output of `mix seed --sample` so I figured I should try it out otherwise. 

Running `mix seed`afterwards and using that new seed didn't work.

Running `mix reset` to start off fresh (and it included a `mix seed`) didn't work either. I could still create the token, access it based on its ID, but still no luck on `/minted_tokens.all`.

**Comment by mederic-p** [comment]
Hello, can you send the json body that you used in the request?
Make sure that you don't have a `search_term` params that would filter the results.

**Comment by kartsims** [comment]
Yes that was it, I had to empty the `search_term` parameter, thank you !

I'd like to share my opinion on this endpoint before closing this issue if you don't mind :

- I'd except `search_term` to be empty in the example payload. In most APIs I've used, this is either an optional parameter or defaults to an empty string
- There seems to be no maximum for `per_page`. I didn't check the code implementation but I guess there actually is a maximum, even a high one (this might actually be a completely separate issue)
- I didn't understand why adding the `--sample` parameter in the `mix seed` command showed a completely different output. It should probably the same one, shouldn't it ? Maybe a text at the end stating that sample data has been added... I may not be grasping the difference as I haven't tinkered enough with the sample data so please forgive me if I'm making a false statement.

I'm loving what I see, and was expecting this release to play with. So far my experience has been quite good, easy onboarding process and enough doc to get started... Thanks a lot and congratulations to the team !

**Comment by T-Dnzt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove `search_term(s)` from Swagger doc](https://trello.com/c/WuXFFYa8/54-remove-searchterms-from-swagger-doc)

**Comment by T-Dnzt** [comment]
@kartsims Thanks for the feedback and for raising this/these issue(s) ;)

- You're right, we're going to fix that.
- Yup, something we overlooked. We're going to add a configurable maximum `per_page` defaulting to `100`.
- The `mix seed` command is supposed to set up the eWallet for production use and displays the minimum amount of information. The `--sample` version is going to create more data in the db so you can play with it (shouldn't be used in prod). However, you're right, they should probably have a similar output. We'll work on refactoring that (especially with the admin panel being merged soon).

> I'm loving what I see, and was expecting this release to play with. So far my experience has been quite good, easy onboarding process and enough doc to get started... Thanks a lot and congratulations to the team !

Thank you, we're very happy to hear that!
