### ISSUE TITLE
Remove waffles badge from main README

### ISSUE THREAD

**Issue by unnawut** [omisego/ewallet#974]
**Describe the bug**

Waffles no longer used. Its badge must go.

**To Reproduce**
1. Go to https://github.com/omisego/ewallet
2. It's right there.

**Expected behavior**
Waffles badge is removed, or replaced with GitHub project badges.

**Comment by sirn** [comment]
I don't think there's GitHub Projects badges. Maybe replace it this? :point_down:

![](https://img.shields.io/github/issues/omisego/ewallet.svg)

```
![](https://img.shields.io/github/issues/omisego/ewallet.svg)
```

**Comment by unnawut** [comment]
Yeah sounds good. Would be nice to have `issues # closed` badge too for comparison.

**Comment by Macavirus** [comment]
"Issues closed" is an open PR for a new badge type but not yet merged: https://github.com/badges/shields/issues/2536

**Comment by unnawut** [comment]
Thanks @Macavirus !
