### ISSUE TITLE
mix seed shouldn't error if the BASE_URL wasn't set

### ISSUE THREAD

**Issue by sirn** [omisego/ewallet#98]
# Subject of the issue

`mix seed` shouldn't error if the `BASE_URL` wasn't set.

# Your environment

```
$ uname -a
Linux srv1 4.4.86+ #1 SMP Thu Dec 7 20:11:11 PST 2017 x86_64 GNU/Linux
```

# Steps to reproduce

Leave out `BASE_URL` when running `mix seed`

# Expected behavior

Seed works with URL fallback to `example.com` or something.

# Actual behavior

Without `BASE_URL`:

```shell
$ env |grep ^BASE_URL
$ mix seed
** (ArgumentError) argument error
    apps/ewallet/priv/repo/report_minimum.exs:5: (file)
    (elixir) lib/code.ex:334: Code.load_file/2
```

With `BASE_URL`:

```
$ env BASE_URL=http://www.example.com/ mix seed
...snip...
Database seeding completed. Enjoy!
```

**Comment by sirn** [comment]
Also `BASE_URL` handling should properly handle URL with trailing slash and one without. Currently this is causing the URL to be generated as `http://www.example.com//path` (double /) in some place while running seeds.

**Comment by unnawut** [comment]
I'm going to rethink a bit about [the](https://hackernoon.com/developer-experience-dx-devs-are-people-too-6590d6577afe) [whole](https://blog.argoproj.io/building-the-developer-experience-dx-from-the-ground-up-8254d50457f5?gi=13652129b9e) [developer](https://www.heroku.com/dx) [experience](http://softwareas.com/patterns-of-developer-experience) setting up the eWallet. So I'll separate this into 2 parts:

1. Fix the exception. Will do now.
2. See if there's a better way to manage env vars / sanity check for missing env vars before allowing commands to run. This is for this week or next.

**Comment by unnawut** [comment]
@sirn Can you find out what Mix.env it's being run on? I'm curious because `:dev` and `:test` environment do have default `:base_url` values at the moment:

```ex
config :ewallet_db,
  base_url: System.get_env("BASE_URL") || "http://localhost:4000"
```

Also... do you think defaulting to `https://localhost:4000` should this apply to `:prod` as well? In the current code, `:prod` environment is the one that does not have a default.

**Comment by sirn** [comment]
```shell
$ echo $MIX_ENV
prod
```

However, we should probably set this default only for seeds. Since seeds is a one-off script, and we should never assume it will have all environment variables set, especially if the environment variable was only for generating report output. In this case, `example.com` is a much better choice.

In other words, let's handle default here for seeds :-)

https://github.com/omisego/ewallet/blob/5f45118f4d282a4e7cdf668e7c242cf176b0b567/apps/ewallet/priv/repo/report_minimum.exs#L5
