### ISSUE TITLE
API: Use a single base_amount string instead of amount & subunit_to_unit

### ISSUE THREAD

**Issue by unnawut** [omisego/ewallet#999]
**Is your feature request related to a problem? Please describe.**

Entertaining @jarindr's idea that we should allow users to make requests by passing the amount in decimal points as a string.

This is because cryptocurrencies are generally much more varied in terms of subunits than fiat currencies. So using amount with subunit_to_unit can be very confusing to developers and anyone who need to touch the API, user-unfriendly and prone to human errors.

**Describe the solution you'd like**

Instead of `{amount: 10000, subunit_to_unit: 100}` representing 100.00 USD, allow passing it as `{amount: "100.00"}` (or `{base_amount: "100.00"}` to keep the separation?) where the value is always a string.

This applies to response values as well.

**Additional context**

This would only apply to the API layer only. The calculations behind the scene would be using either subunits or decimals.

**Comment by sirn** [comment]
Ideas

**Comment by unnawut** [comment]
Still prone to conversion error when converting from string to float
